// fastdl.lua generated by FastDL Generator.
if (SERVER) then
 resource.AddFile("materials/drgbase/icon16.png")
 resource.AddFile("materials/drgbase/stick_boi/climb1.png")
 resource.AddFile("materials/drgbase/stick_boi/climb2.png")
 resource.AddFile("materials/drgbase/stick_boi/idle1.png")
 resource.AddFile("materials/drgbase/stick_boi/idle2.png")
 resource.AddFile("materials/drgbase/stick_boi/idle3.png")
 resource.AddFile("materials/drgbase/stick_boi/idle4.png")
 resource.AddFile("materials/drgbase/stick_boi/jump1.png")
 resource.AddFile("materials/drgbase/stick_boi/walk1.png")
 resource.AddFile("materials/drgbase/stick_boi/walk2.png")
 resource.AddFile("materials/entities/drgbase_possessor.png")
 resource.AddFile("materials/entities/npc_drg_testhuman.png")
 resource.AddFile("materials/entities/npc_drg_testnextbot.png")
 resource.AddFile("particles/drgbase.pcf")
end